- hosts: all
  become: yes
  vars:
    api_private_ip: "{{ lookup('env', 'INSTANCE_IP_PRIVATE') }}"
  tasks:
    - name: Vérifier que api_private_ip est bien définie
      fail:
        msg: "La variable api_private_ip (INSTANCE_IP_PRIVATE) n'est pas définie !"
      when: api_private_ip is undefined or api_private_ip == ""
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Démarrer Nginx
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Installer Node.js et npm
      apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes
    - name: Copier les fichiers du front dans /var/www/html/
      copy:
        src: ../todolist-app/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: "0755"
    - name: Copier la configuration nginx personnalisée depuis un template
      template:
        src: ../nginx/nginx.conf.j2
        dest: /etc/nginx/sites-available/ma-todo.conf
        owner: root
        group: root
        mode: "0644"
    - name: Activer la configuration nginx personnalisée
      file:
        src: /etc/nginx/sites-available/ma-todo.conf
        dest: /etc/nginx/sites-enabled/ma-todo.conf
        state: link
        force: yes
    - name: Supprimer la configuration par défaut de nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: Vérifier la configuration nginx
      command: nginx -t
      register: nginx_test
      changed_when: false
      failed_when: nginx_test.rc != 0

    - name: Recharger nginx
      service:
        name: nginx
        state: reloaded
