---
- name: Installer et configurer PostgreSQL pour l'application todos
  hosts: all
  become: yes
  vars:
    pg_user: todo_user
    pg_db: todos
    pg_password: todo_super_secret_password

  tasks:
    - name: Installer PostgreSQL
      apt:
        name: postgresql
        state: present
        update_cache: yes

    - name: S'assurer que le service PostgreSQL est démarré
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Installer le package python pour PostgreSQL
      apt:
        name: python3-psycopg2
        state: present

    - name: Créer l'utilisateur PostgreSQL
      become: true
      become_user: postgres
      become_method: su
      community.postgresql.postgresql_user:
        name: "{{ pg_user }}"
        password: "{{ pg_password }}"
        state: present

    - name: Créer la base de données PostgreSQL
      become: true
      become_user: postgres
      become_method: su
      community.postgresql.postgresql_db:
        name: "{{ pg_db }}"
        owner: "{{ pg_user }}"
        state: present

    - name: Créer la table todos
      become: true
      become_user: postgres
      become_method: su
      community.postgresql.postgresql_query:
        db: "{{ pg_db }}"
        query: |
          CREATE TABLE IF NOT EXISTS todos (
            id SERIAL PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            completed BOOLEAN NOT NULL DEFAULT FALSE
          );
            completed BOOLEAN NOT NULL DEFAULT FALSE
          );
