- hosts: all
  become: yes
  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Démarrer Nginx
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Installer Node.js et npm
      apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes
    - name: Copier les fichiers du front dans /var/www/html/
      copy:
        src: ../todolist-app/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: "0755"
