- hosts: all
  become: yes
  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Démarrer Nginx
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Installer Node.js et npm
      apt:
        name:
          - nodejs
          - npm
        state: present
        update_cache: yes
    - name: Installer les dépendances Node.js de l'app
      args:
        chdir: /home/ubuntu/app-web
      npm:
        path: /home/ubuntu/app-web
        production: yes
    - name: Lancer l'application Node.js en arrière-plan
      become: false
      args:
        chdir: /home/ubuntu/app-web
      shell: |
        nohup npm start > app.log 2>&1 &
