- hosts: all
  become: yes
  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Démarrer Nginx
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Installer Python3 et pip
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes
    - name: Installer les dépendances Python de l'app
      pip:
        requirements: /home/ubuntu/app-web/requirements.txt
        executable: pip3
    - name: Lancer l'application Flask en arrière-plan
      become: false
      args:
        chdir: /home/ubuntu/app-web
      shell: |
        nohup python3 app.py > app.log 2>&1 &
