---
- name: Installer et configurer MySQL pour l'application todos
  hosts: all
  become: yes
  vars:
    mysql_root_password: "root_super_secret_password"
    mysql_user: "todo_user"
    mysql_db: "todos"
    mysql_password: "todo_super_secret_password"

  tasks:
    - name: Installer le serveur MySQL (MariaDB)
      apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: S'assurer que le service MySQL est démarré
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Installer le package python pour MySQL
      apt:
        name: python3-pymysql
        state: present

    - name: Forcer l'authentification root en mysql_native_password
      mysql_user:
        name: root
        host_all: true
        plugin: mysql_native_password
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Définir le mot de passe root de MySQL
      mysql_user:
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
        user: root
        password: "{{ mysql_root_password }}"
        host_all: true
        check_implicit_admin: true

    - name: Créer la base de données todos
      community.mysql.mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Créer l'utilisateur todo_user
      community.mysql.mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        host: "%"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Créer la table todos
      community.mysql.mysql_query:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        db: "{{ mysql_db }}"
        query: |
          CREATE TABLE IF NOT EXISTS todos (
            id INT AUTO_INCREMENT PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            completed BOOLEAN NOT NULL DEFAULT FALSE
          );

  handlers:
    - name: Redémarrer PostgreSQL
      service:
        name: postgresql
        state: restarted
