- hosts: all
  become: yes
  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Démarrer Nginx
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Copier la clé privée sur l'instance publique
      copy:
        src: ~/.ssh/iia-2025.pem
        dest: /home/ubuntu/iia-2025.pem
        owner: ubuntu
        group: ubuntu
        mode: "0400"
