- hosts: all
  become: yes
  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Démarrer Nginx
      service:
        name: nginx
        state: started
        enabled: yes
